[phases.setup]
nixPkgs = ['php83', 'php83Packages.composer', 'nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs',
    'npm ci --only=production',
    'npm run build'
]

[phases.build]
cmds = [
    'php artisan cache:clear',
    'php artisan config:clear',
    'php artisan route:clear',
    'php artisan view:clear',
    'php artisan storage:link',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'
